spring:
  datasource:
      username: sa
      password: ""
      platform: h2
      driverClassName: org.h2.Driver
      url: "jdbc:h2:file:./purchase-transactions"
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
      hibernate.ddl-auto: update
      show-sql: true
  main:
      allow-bean-definition-overriding: true
      
  h2:
      console:
        enabled: true
